run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - govet
    - staticcheck
    - revive
    - unused
    - errname
    - errorlint
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - predeclared

linters-settings:
  govet:
    check-shadowing: true
  lll:
    line-length: 150
  misspell:
    locale: US
