name: Code build and checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --enable revive --timeout=5m
          only-new-issues: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up JMeter
        run: |
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.zip
          unzip apache-jmeter-5.5.zip
          mv apache-jmeter-5.5 jmeter
          sudo mv jmeter /opt
          echo "/opt/jmeter/bin" >> $GITHUB_PATH

      - name: Integration test
        run: go test --tags=integration -v ./...
